article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.halamanArtikel, name='halamanArtikel'),
    path('melihatArtikel/<str:idArtikel>', views.melihatArtikel, name='melihatArtikel'),
    path('membuatArtikel/', views.membuatArtikel, name='membuatArtikel'),
    path('mengelolaArtikel/', views.mengelolaArtikel, name='mengelolaArtikel'),
    path('mengubahArtikel/<str:idArtikel>', views.mengubahArtikel, name='mengubahArtikel'),
    path('menghapusArtikel/<str:idArtikel>', views.menghapusArtikel, name='menghapusArtikel'),
]

barang/urls.py
from django.urls import path
from .views import *

app_name = 'barang'

urlpatterns = [
    path('', listBarang, name='listBarang'),
    path('update_barang/', updateBarang, name='update'),
    path('konfirmasi_update/<id>/', konfirmasiUpdate, name='konfirmasiUpdate'),
    path('hapus_barang/', hapusBarang, name='hapus'),
    path('konfirmasi_hapus/<id>/', konfirmasiHapus, name='konfirmasiHapus'),
    path('tambah_barang/', tambahBarang, name='tambah'),
]

donasi/urls.py
from django.urls import path
from .views import *

app_name = 'donasi'

urlpatterns = [
    path('', donasipage, name='donasipage'),
    path('riwayat-donasi/', riwayatdonasi, name='riwayatdonasi'),
    path('lembaga-sosial/formulir-donasi/', formulirdonasi, name='formulirdonasi'),
    path('admin/pembatalan-donasi/', adminDaftarPembatalandonasi, name='pembatalandonasi'),
    path('create-lembaga-sosial/', createLembagaSosial, name='createLembagaSosial'),
    path('delete-all/', deleteAllDonasi, name='deleteAllDonasi'),
]

loginin/urls.py
from django.urls import path
from .views import loginin,signup
#url for app

app_name = 'loginin'

urlpatterns = [
    path('', loginin,name ='loginin'),
    path('signup/', signup ,name ='signup'),
]

shop/urls.py
from django.urls import path
from .views import shoppage, checkout, riwayat, deskripsi, tambahBarangKeranjang, keranjangModal, hapusBarangKeranjang, checkoutModal, createTrx, riwayatModal, pembayaranTrx, konfirmasiSampai

app_name = 'shop'

urlpatterns = [
    path('', shoppage, name='shoppage'),
    path('pembayaran/<id>', checkout, name='checkout'),
    path('riwayat_transaksi/', riwayat, name='riwayat'),
    path('deskripsi/<id>/', deskripsi, name='deskripsi'),
    path('tambah_barang_keranjang/', tambahBarangKeranjang, name='tambahBarangKeranjang'),
    path('modal_keranjang/', keranjangModal, name='keranjangModal'),
    path('modal_checkout/', checkoutModal, name='checkoutModal'),
    path('modal_riwayat/', riwayatModal, name='riwayatModal'),
    path('hapus_barang_keranjang/', hapusBarangKeranjang, name='hapusBarangKeranjang'),
    path('create_transaksi/', createTrx, name='createTrx'),
    path('pembayaran/', pembayaranTrx, name='pembayaran'),
    path('sampai/', konfirmasiSampai, name='pembayaran'),
]

solink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('shop/', include('shop.urls')),
    path('barang/', include('barang.urls')),
    path('donasi/', include('donasi.urls')),
    path('mitra/', include('shop.mitra_urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loginin/', include('loginin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

home/templates/navbar.html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SoLink</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400&display=swap" rel="stylesheet">
</head>

<style>
  .navbar-nav > li{
    margin-left:6px;
    margin-right:6px;
  }
</style>
{% block style %}{% endblock %}

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #679186;">
    <a class="navbar-brand" href="{% url 'article:halamanArtikel' %}" style="font-family: 'Caveat', cursive; font-weight: 700;">SoLink</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        {% if user.profile.role == "Admin" %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'article:mengelolaArtikel' %}">Kelola Artikel <span></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'donasi:pembatalandonasi' %}">Validasi Pembatalan Donasi <span></span></a>
        </li>
        {% endif %}
        {% if user.profile.role == "Mitra" %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'barang:listBarang' %}">Kelola Barang <span></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'mtr_shop:penjualan' %}">Transaksi Penjualan <span></span></a>
        </li>
        {% endif %}
        {% if user.profile.role == "Lembaga Sosial" %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'donasi:formulirdonasi' %}">Daftar Formulir Donasi <span></span></a>
        </li>
        {% endif %}
        {% if user.profile.role == "Kontributor/Pembeli" %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:shoppage' %}">Zero Waste Shop</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'donasi:donasipage' %}">Donasi</span></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'article:halamanArtikel' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'loginin:loginin' %}">Account</span></a>
        </li>
      </ul>
    </div>
</nav>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
  {% block content %}{% endblock %}
</body>