barang/urls.py
from django.urls import path
from .views import *

app_name = 'barang'

urlpatterns = [
    path('', listBarang, name='listBarang'),
    path('update_barang/', updateBarang, name='update'),
    path('konfirmasi_update/<id>/', konfirmasiUpdate, name='konfirmasiUpdate'),
    path('hapus_barang/', hapusBarang, name='hapus'),
    path('konfirmasi_hapus/<id>/', konfirmasiHapus, name='konfirmasiHapus'),
    path('tambah_barang/', tambahBarang, name='tambah'),
]

shop/urls.py
from django.urls import path
from .views import shoppage, checkout, riwayat, deskripsi, tambahBarangKeranjang, keranjangModal, hapusBarangKeranjang, checkoutModal, createTrx, riwayatModal, pembayaranTrx, konfirmasiSampai

app_name = 'shop'

urlpatterns = [
    path('', shoppage, name='shoppage'),
    path('pembayaran/<id>', checkout, name='checkout'),
    path('riwayat_transaksi/', riwayat, name='riwayat'),
    path('deskripsi/<id>/', deskripsi, name='deskripsi'),
    path('tambah_barang_keranjang/', tambahBarangKeranjang, name='tambahBarangKeranjang'),
    path('modal_keranjang/', keranjangModal, name='keranjangModal'),
    path('modal_checkout/', checkoutModal, name='checkoutModal'),
    path('modal_riwayat/', riwayatModal, name='riwayatModal'),
    path('hapus_barang_keranjang/', hapusBarangKeranjang, name='hapusBarangKeranjang'),
    path('create_transaksi/', createTrx, name='createTrx'),
    path('pembayaran/', pembayaranTrx, name='pembayaran'),
    path('sampai/', konfirmasiSampai, name='pembayaran'),
]

solink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('shop/', include('shop.urls')),
    path('barang/', include('barang.urls')),
    path('donasi/', include('donasi.urls')),
    path('mitra/', include('shop.mitra_urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loginin/', include('loginin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

barang/models.py
from django.db import models

# Create your models here.
class Barang(models.Model):
    namaPemilik = models.CharField(max_length = 50)
    idBarang = models.IntegerField()
    namaBarang = models.CharField(max_length = 50)
    deskripsiBarang = models.TextField()
    urlFoto = models.URLField(max_length=200)
    hargaBarang = models.FloatField()
    jumlahStok = models.IntegerField()
    rating = models.FloatField()
    stokRate = models.IntegerField()

    def updateNama(self,nama):
        self.namaBarang = nama
        self.save()
    
    def updateDeskripsi(self,deksripsi):
        self.deskripsiBarang = deksripsi
        self.save()

    def updateFoto(self,urlFoto):
        self.urlFoto =urlFoto
        self.save()
    
    def updateHarga(self,harga):
        self.hargaBarang = harga
        self.save()
    
    def tambahPenilaianRating(self,rate):
        newRating = self.stokRate *self.rating + rate
        self.rating = newRating/(self.stokRate + 1)
        self.stokRate += 1
        self.save()
    
    def getJumlahStok(self):
        return self.jumlahStok
    
    def updateJumlahStok(self,stok):
        self.jumlahStok = stok
        self.save()

barang/forms.py
from django import forms

class TambahBarangForm(forms.Form):
    namaBarang = forms.CharField(max_length = 50)
    urlFoto = forms.URLField(max_length=200)
    hargaBarang = forms.FloatField()
    jumlahStok = forms.IntegerField()
    deskripsiBarang = forms.CharField(widget=forms.Textarea)
    def __init__(self, *args, **kwargs):
        super(TambahBarangForm, self).__init__(*args, **kwargs)
        self.fields['namaBarang'].widget.attrs['class'] = 'form-control'
        self.fields['urlFoto'].widget.attrs['class'] = 'form-control'
        self.fields['hargaBarang'].widget.attrs['class'] = 'form-control'
        self.fields['jumlahStok'].widget.attrs['class'] = 'form-control'
        self.fields['deskripsiBarang'].widget.attrs['class'] = 'form-control'
    
class UpdateBarangForm(TambahBarangForm):
    idBarang = forms.IntegerField(disabled = True)
    ratedStok = forms.IntegerField(disabled = True)
    rating = forms.FloatField(disabled = True)

    def __init__(self, *args, **kwargs):
        super(UpdateBarangForm, self).__init__(*args, **kwargs)
        self.fields['idBarang'].widget.attrs['class'] = 'form-control'
        self.fields['ratedStok'].widget.attrs['class'] = 'form-control'
        self.fields['rating'].widget.attrs['class'] = 'form-control'
        self.fields['idBarang'].initial = '0'
        self.fields['ratedStok'].initial = '0'
        self.fields['rating'].initial = '0'
        self.fields['namaBarang'].initial = 'Nama Barang'
        self.fields['urlFoto'].initial = 'Url Barang'
        self.fields['hargaBarang'].initial = '0'
        self.fields['jumlahStok'].initial = '0'
        self.fields['deskripsiBarang'].initial = 'Deskripsi Barang'

class HapusBarangForm(forms.Form):
    namaBarang = forms.CharField(max_length = 50, disabled = True)
    idBarang = forms.IntegerField(disabled = True)
    def __init__(self, *args, **kwargs):
        super(HapusBarangForm, self).__init__(*args, **kwargs)
        self.fields['idBarang'].initial = '0'
        self.fields['namaBarang'].initial = 'Nama Barang'

barang/views.py
from django.shortcuts import render,redirect
from django.core import serializers
from django.http import HttpResponse,JsonResponse, HttpResponseRedirect
from .forms import *
from .models import *
from django.contrib.auth.models import User
from article.views import halamanArtikel
from loginin.Mitra import Mitra
from django.urls import reverse_lazy

# Create your views here.
def listBarang(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Mitra":
            username = request.user.username
            mitra = Mitra(username)
            data = mitra.barangMitra()
            return render(request, 'barang.html',{'data':data})
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def tambahBarang(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Mitra":
            if request.method == "POST":
                namaPemilik = request.user.username
                if Barang.objects.all().count() == 0:
                    idBarang = 1
                else :
                    idBarang = Barang.objects.order_by('-idBarang')[0].idBarang + 1
                namaBarang = request.POST['namaBarang']
                deskripsiBarang = request.POST['deskripsiBarang']
                urlFoto = request.POST['urlFoto']
                hargaBarang = request.POST['hargaBarang']
                jumlahStok = request.POST['jumlahStok']
                rating = 0
                stokRate = 0
                barang = Barang(namaPemilik=namaPemilik,idBarang=idBarang,namaBarang=namaBarang,deskripsiBarang=deskripsiBarang,
                urlFoto=urlFoto,hargaBarang=hargaBarang,jumlahStok=jumlahStok,rating=rating,stokRate=stokRate)
                mitra = Mitra(namaPemilik)
                mitra.menambahkanBarang(barang)
                return redirect('/barang/')
            else:
                form = TambahBarangForm()
                return render(request,'tambahBarang.html', {'form': form})
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def updateBarang(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Mitra":
            username = request.user.username
            mitra = Mitra(username)
            data = mitra.barangMitra()
            return render(request, 'updateBarang.html',{'data':data})
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def konfirmasiUpdate(request,id):
    if request.user.is_authenticated:
        if request.user.profile.role == "Mitra":
            if request.method == "POST":
                namaBarang = request.POST['namaBarang']
                deskripsiBarang = request.POST['deskripsiBarang']
                urlFoto = request.POST['urlFoto']
                hargaBarang = request.POST['hargaBarang']
                jumlahStok = request.POST['jumlahStok']
                barang = Barang.objects.get(idBarang=id)
                barang.updateNama(namaBarang)
                barang.updateDeskripsi(deskripsiBarang)
                barang.updateFoto(urlFoto)
                barang.updateHarga(hargaBarang)
                barang.updateJumlahStok(jumlahStok)
                return redirect('/barang/')
            else:
                dataBarang = Barang.objects.all().filter(idBarang=id)
                form = UpdateBarangForm()
                for data in dataBarang:
                    form.fields['idBarang'].initial = data.idBarang
                    form.fields['ratedStok'].initial = data.stokRate
                    form.fields['rating'].initial = data.rating
                    form.fields['namaBarang'].initial = data.namaBarang
                    form.fields['urlFoto'].initial = data.urlFoto
                    form.fields['hargaBarang'].initial = data.hargaBarang
                    form.fields['jumlahStok'].initial = data.jumlahStok
                    form.fields['deskripsiBarang'].initial = data.deskripsiBarang
                return render(request, 'konfirmasiUpdate.html', {'form': form})
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def hapusBarang(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Mitra":
            username = request.user.username
            mitra = Mitra(username)
            data = mitra.barangMitra()
            return render(request, 'hapusBarang.html',{'data':data})
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def konfirmasiHapus(request,id):
    if request.user.is_authenticated:
        if request.user.profile.role == "Mitra":
            if request.method == "POST":
                namaPemilik = request.user.username
                mitra = Mitra(namaPemilik)
                mitra.menghapusBarang(id)
                return redirect('/barang/')
            else :
                dataBarang = Barang.objects.all().filter(idBarang=id)
                form = HapusBarangForm()
                for barang in dataBarang:
                    form.fields['idBarang'].initial = barang.idBarang
                    form.fields['namaBarang'].initial = barang.namaBarang
                    foto = barang.urlFoto
                return render(request, "konfirmasiHapus.html",{'form':form,'image':foto})
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

    

barang/templates/barang.html
{% extends 'navbar.html' %}
{% load static %}
{% block style %}
  <style>
    #titleID {
        content: Kelola Barang - SoLink;
    }
    .wrap{
    position: relative;
    }
    .wrap a{
      position: absolute;
      width:100%;
      height:100%;
      top:0px;
      left:0px;
    }
  </style>
{% endblock %}
{% block content %}
<div class="container" style="margin-top: 2%;">
  <div class="row">
    <div class="col">
        <h1 style="font-family: 'Caveat', cursive;">Kelola Barang</h1>
    </div>
    <div class="col-2">
      <a href="{% url 'barang:tambah' %}">
          <button type="button" class="btn btn-outline-dark" style="float: right;">
              Tambahkan Barang
          </button>
      </a>
    </div>
    <div class="col-2">
      <a href="{% url 'barang:update' %}">
          <button type="button" class="btn btn-outline-dark" style="float: right;">
              Update Barang
          </button>
      </a>
    </div>
    <div class="col-2">
      <a href="{% url 'barang:hapus' %}">
          <button type="button" class="btn btn-outline-dark" style="float: right;">
              Hapus Barang
          </button>
      </a>
  </div>
</div>

<div class="container" style="margin-top: 2%;">
  <div class="row row-cols-2 row-cols-sm-4" style="margin-top: 1%;">
    {% for item in data %}
    <div class="col mb-4">
      <div class="card h-100">
        <img src="{{ item.urlFoto }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ item.namaBarang }}</h5>
          <div class="text-left">
              <p class="card-text">Harga Barang : {{ item.hargaBarang }}</p>
              <p class="card-text">Stok Barang : {{ item.jumlahStok }}</p>
              <p class="card-text">Deskripsi Barang :{{ item.deskripsiBarang }}</p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>  
</div>
{% endblock %}

barang/templates/hapusBarang.html
{% extends 'navbar.html' %}
{% load static %}
<head>
  <title>Kelola Barang - SoLink</title>
  <style>
    img {
        object-fit: contain;
        max-height: 250px;
    }
    </style>
</head>
{% block content %}
<div class="container" style="margin-top: 2%;">
  <div class="row">
    <div class="col">
        <h1 style="font-family: 'Caveat', cursive;">Hapus Barang</h1>
    </div>
    <div class="col-2">
      <a href="{% url 'barang:listBarang' %}">
          <button type="button" class="btn btn-outline-dark" style="float: right;">
            Kembali
          </button>
      </a>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 2%;">
  <div class="row row-cols-2 row-cols-sm-4" style="margin-top: 1%;">
    {% for item in data %}
    <div class="col mb-4">
      <div class="card h-100">
        <img src="{{ item.urlFoto }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ item.namaBarang }}</h5>
          <div class="text-right">
              <p class="card-text">{{ item.hargaBarang }}</p>
          </div>
          <div>
            <a href="{% url 'barang:konfirmasiHapus' item.idBarang %}">
            <button class="btn btn-outline-dark" style="float: right;">Hapus</button>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>  
</div>

{% endblock %}

barang/templates/konfirmasiHapus.html
{% extends "navbar.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="konfirmasiHapusLabel">Hapus Barang !!!</h5>
        </div>
        <div class="modal-body">
            <img src="{{ image }}" class="card-img-top">
            <h3>Apakah anda akan menghapus <strong>{{ form.namaBarang }}</strong>?</h3>
            <input type="submit" name="submit" value ="Delete" class="btn btn-outline-success" id ="tombol">
            <a href="{% url 'barang:listBarang' %}" class="btn btn-outline-primary" role="button">Back</a>
        </div>
      </div>
    </div>
  </form>

{% endblock %}

barang/templates/konfirmasiUpdate.html
{% extends "navbar.html" %}

{% block content %}
<div class="container" style="margin-top: 2%;">
    <div class="row">
        <div class="col">
            <h1 style="font-family: 'Caveat', cursive;">Update Barang</h1>
        </div>
        
        <div class="col-2">
            <a href="{% url 'barang:listBarang' %}">
                <button type="button" class="btn btn-outline-dark" style="float: right;">
                    Kembali
                </button>
            </a>
        </div>
    </div>
    
    <div class="centered">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value ="Update" class="btn btn-outline-success" id ="tombol">
            <a href="{% url 'barang:update' %}" class="btn btn-outline-success" role="button">Back</a>
            <p>  </p>
        </form>
    </div>

</div>

{% endblock %}

barang/templates/tambahBarang.html
{% extends 'navbar.html' %}

{% block content %} 

{{ form.non_field_errors }}
<div class="container" style="margin-top: 2%;">
    <div class="row">
        <div class="col">
            <h1 style="font-family: 'Caveat', cursive;">Tambah Barang</h1>
        </div>
        
        <div class="col-2">
            <a href="{% url 'barang:listBarang' %}">
                <button type="button" class="btn btn-outline-dark" style="float: right;">
                    Kembali
                </button>
            </a>
        </div>
    </div>
    
    <form method="POST">
        {% csrf_token %}
        <div class="fieldWrapper">
            {{ form.subject.errors }}
            <div class="row">
                <div class="col-2">
                    <label for="{{ form.subject.id_for_label }}">Nama Barang:</label>
                </div>
                <div class="col">
                    {{ form.namaBarang }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            {{ form.subject.errors }}
            <div class="row">
                <div class="col-2">
                    <label for="{{ form.subject.id_for_label }}">UrlFoto:</label>
                </div>
                <div class="col">
                    {{ form.urlFoto }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            {{ form.subject.errors }}
            <div class="row">
                <div class="col-2">
                    <label for="{{ form.subject.id_for_label }}">Harga Barang:</label>
                </div>
                <div class="col">
                    {{ form.hargaBarang }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            {{ form.subject.errors }}
            <div class="row">
                <div class="col-2">
                    <label for="{{ form.subject.id_for_label }}">Jumlah Stok:</label>
                </div>
                <div class="col">
                    {{ form.jumlahStok }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            {{ form.subject.errors }}
            <div class="row">
                <div class="col-2">
                    <label for="{{ form.subject.id_for_label }}">Deskripsi Barang:</label>
                </div>
                <div class="col">
                    {{ form.deskripsiBarang }}
                </div>
            </div>
        </div>
        <input type="submit" name="submit" value ="Submit" class="btn btn-outline-success" id ="tombol">
    </form>
</div>

{% endblock %}

barang/templates/updateBarang.html
{% extends 'navbar.html' %}
{% load static %}
{% block style %}
<head>
  <title>Kelola Barang - SoLink</title>
  <style>
    img {
        object-fit: contain;
        max-height: 250px;
    }
    </style>
</head>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 2%;">
  <div class="row">
    <div class="col">
        <h1 style="font-family: 'Caveat', cursive;">Update Barang</h1>
    </div>
    <div class="col-2">
      <a href="{% url 'barang:listBarang' %}">
          <button type="button" class="btn btn-outline-dark" style="float: right;">
            Kembali
          </button>
      </a>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 2%;">
  <div class="row row-cols-2 row-cols-sm-4" style="margin-top: 1%;">
    {% for item in data %}
    <div class="col mb-4">
      <div class="card h-100">
        <img src="{{ item.urlFoto }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ item.namaBarang }}</h5>
          <div class="text-right">
              <p class="card-text">{{ item.hargaBarang }}</p>
          </div>
          <div>
            <a href="{% url 'barang:konfirmasiUpdate' item.idBarang %}">
            <button class="btn btn-outline-dark" style="float: right;">Update</button>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>  
</div>
{% endblock %}