article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.halamanArtikel, name='halamanArtikel'),
    path('melihatArtikel/<str:idArtikel>', views.melihatArtikel, name='melihatArtikel'),
    path('membuatArtikel/', views.membuatArtikel, name='membuatArtikel'),
    path('mengelolaArtikel/', views.mengelolaArtikel, name='mengelolaArtikel'),
    path('mengubahArtikel/<str:idArtikel>', views.mengubahArtikel, name='mengubahArtikel'),
    path('menghapusArtikel/<str:idArtikel>', views.menghapusArtikel, name='menghapusArtikel'),
]

shop/urls.py
from django.urls import path
from .views import shoppage, checkout, riwayat, deskripsi, tambahBarangKeranjang, keranjangModal, hapusBarangKeranjang, checkoutModal, createTrx, riwayatModal, pembayaranTrx, konfirmasiSampai

app_name = 'shop'

urlpatterns = [
    path('', shoppage, name='shoppage'),
    path('pembayaran/<id>', checkout, name='checkout'),
    path('riwayat_transaksi/', riwayat, name='riwayat'),
    path('deskripsi/<id>/', deskripsi, name='deskripsi'),
    path('tambah_barang_keranjang/', tambahBarangKeranjang, name='tambahBarangKeranjang'),
    path('modal_keranjang/', keranjangModal, name='keranjangModal'),
    path('modal_checkout/', checkoutModal, name='checkoutModal'),
    path('modal_riwayat/', riwayatModal, name='riwayatModal'),
    path('hapus_barang_keranjang/', hapusBarangKeranjang, name='hapusBarangKeranjang'),
    path('create_transaksi/', createTrx, name='createTrx'),
    path('pembayaran/', pembayaranTrx, name='pembayaran'),
    path('sampai/', konfirmasiSampai, name='pembayaran'),
]

solink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('shop/', include('shop.urls')),
    path('barang/', include('barang.urls')),
    path('donasi/', include('donasi.urls')),
    path('mitra/', include('shop.mitra_urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loginin/', include('loginin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from datetime import datetime

from ckeditor.fields import RichTextField

# Create your models here.
class Artikel(models.Model):
    judulArtikel = models.CharField(max_length=50)
    abstraksiArtikel = models.TextField(max_length=360)
    isiArtikel = RichTextField(blank=True, null=True)
    idArtikel = models.IntegerField(unique=True)
    timestamp = models.DateTimeField(default=datetime.now)
    gambarThumbnail = models.ImageField(upload_to = 'thumbnail_folder/', default = 'thumbnail_folder/None/no-img.jpg')

    def __str__(self):
        return self.judulArtikel

    def setJudul(self,judul):
        self.judulArtikel = judul
        self.save()

    def setAbstraksi(self,abstraksi):
        self.abstraksiArtikel = abstraksi
        self.save()

    def setIsi(self,isi):
        self.isiArtikel = isi
        self.save()

    def setThumbnail(self,gambar):
        self.gambarThumbnail = gambar
        self.save()
    

article/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

class membuatArtikelForm(forms.Form):
    judulArtikel = forms.CharField(label='Judul Artikel',max_length=50, widget=forms.TextInput(attrs={'placeholder':'Max : 50 char'}))
    abstraksiArtikel = forms.CharField(label='Abstraksi Singkat',max_length=360, widget=forms.Textarea(attrs={'rows': 8, 'placeholder':'Max : 360 char'}))
    isiArtikel = forms.CharField(label='Isi Artikel', widget=CKEditorWidget())
    gambarThumbnail = forms.ImageField(label='Gambar Thumbnail')
    def __init__(self, *args, **kwargs):
        super(membuatArtikelForm, self).__init__(*args, **kwargs)
        self.fields['judulArtikel'].widget.attrs['class'] = 'form-control'
        self.fields['abstraksiArtikel'].widget.attrs['class'] = 'form-control'
        self.fields['isiArtikel'].widget.attrs['class'] = 'form-control'
        

class mengubahArtikelForm(forms.Form):
    idArtikel = forms.IntegerField(label='ID Artikel', disabled = True)
    judulArtikel = forms.CharField(label='Judul Artikel',max_length=50, widget=forms.TextInput())
    abstraksiArtikel = forms.CharField(label='Abstraksi Singkat',max_length=360, widget=forms.Textarea(attrs={'rows': 8}))
    isiArtikel = forms.CharField(label='Isi Artikel', widget=CKEditorWidget())
    gambarThumbnail = forms.ImageField(label='Gambar Thumbnail')

    def __init__(self, *args, **kwargs):
        super(mengubahArtikelForm, self).__init__(*args, **kwargs)
        self.fields['judulArtikel'].widget.attrs['class'] = 'form-control'
        self.fields['abstraksiArtikel'].widget.attrs['class'] = 'form-control'
        self.fields['isiArtikel'].widget.attrs['class'] = 'form-control'

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from loginin.AdminClass import Admin
from .forms import *
from .models import *


# Create your views here.
def halamanArtikel(request):
    artikel = Artikel.objects.all().order_by('-timestamp')
    args = {
        'artikel': artikel,
    }
    return render(request, 'halamanArtikel.html', args)

def melihatArtikel(request, idArtikel):
    message = ""
    artikel = ""
    try :
        artikel = Artikel.objects.filter(idArtikel=idArtikel)
    except :
        message = "Gagal menampilkan artikel"
    args = {
        'artikel': artikel,
        'message': message
    }
    return render(request, 'melihatArtikel.html', args)

def membuatArtikel(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Admin":
            username = request.user.username
            admin = Admin(username)
            if request.method == "POST":
                input = request.POST
                judulArtikel = input['judulArtikel']
                abstraksiArtikel = input['abstraksiArtikel']
                isiArtikel = input['isiArtikel']
                gambarThumbnail = request.FILES['gambarThumbnail']
                if Artikel.objects.all().count() == 0:
                    idArtikel = 1
                else :
                    idArtikel = Artikel.objects.order_by('-idArtikel')[0].idArtikel + 1
                try : 
                    artikel = Artikel(judulArtikel=judulArtikel, abstraksiArtikel=abstraksiArtikel, isiArtikel=isiArtikel, idArtikel=idArtikel, gambarThumbnail=gambarThumbnail)
                    admin.membuatArtikel(artikel)
                    message = 'Artikel dengan judul "' + judulArtikel + '" berhasil dibuat'
                except :
                    message = "Gagal membuat Artikel"
                request.session['pesan'] = message
                return HttpResponseRedirect('/mengelolaArtikel/')
            form = membuatArtikelForm()
            args = {
                'form':form,
            }
            return render(request, 'membuatArtikel.html', args)
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def mengelolaArtikel(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Admin":
            artikel = Artikel.objects.all().order_by('-timestamp')
            message = ""
            try :
                message = request.session.get('pesan')
                del request.session['pesan']
            except :
                message = ""
            args = {
                'artikel': artikel,
                'message': message
            }
            return render(request, 'mengelolaArtikel.html', args)
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def mengubahArtikel(request, idArtikel):
    if request.user.is_authenticated:
        if request.user.profile.role == "Admin":
            username = request.user.username
            admin = Admin(username)
            artikelObj = Artikel.objects.filter(idArtikel=idArtikel)
            artikelGet = admin.getArtikel(idArtikel)
            judulArtikelObj = artikelObj[0].judulArtikel
            abstraksiArtikelObj = artikelObj[0].abstraksiArtikel
            isiArtikelObj = artikelObj[0].isiArtikel
            gambarThumbnailObj = artikelObj[0].gambarThumbnail
            form = mengubahArtikelForm(initial={'idArtikel' : idArtikel, 'judulArtikel' : judulArtikelObj, 'abstraksiArtikel' : abstraksiArtikelObj, 'isiArtikel' : isiArtikelObj, 'gambarThumbnail' : gambarThumbnailObj})
            if request.method == "POST":
                input = request.POST
                judulArtikel = input['judulArtikel']
                abstraksiArtikel = input['abstraksiArtikel']
                isiArtikel = input['isiArtikel']
                try :
                    gambarThumbnail = request.FILES['gambarThumbnail']
                    artikelGet.gambarThumbnail.delete(save=True)
                    artikelGet.setThumbnail(gambarThumbnail)
                except :
                    pass
                try :
                    admin.mengubahArtikel(idArtikel, judulArtikel, abstraksiArtikel, isiArtikel)
                    message = 'Artikel dengan judul "' + judulArtikel + '" berhasil diubah'
                except :
                    message = "Gagal mengubah Artikel"
                request.session['pesan'] = message
                return HttpResponseRedirect('/mengelolaArtikel/')
            args = {
                'form':form,
                'idArtikel':idArtikel
            }
            return render(request, 'mengubahArtikel.html', args)
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))

def menghapusArtikel(request, idArtikel):
    if request.user.is_authenticated:
        if request.user.profile.role == "Admin":
            username = request.user.username
            admin = Admin(username)
            try :
                artikelGet = admin.getArtikel(idArtikel)
                message = 'Artikel dengan judul "' + artikelGet.judulArtikel + '" berhasil terhapus'
                admin.menghapusArtikel(idArtikel)
            except Exception:
                message = "Gagal menghapus!!! Artikel tidak tersedia / sudah terhapus"
            request.session['pesan'] = message
            return HttpResponseRedirect('/mengelolaArtikel/')
    return HttpResponseRedirect(reverse_lazy('article:halamanArtikel'))
    

article/templates/halamanArtikel.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoLink</title>
    <link href="{% static 'ionicons-2.0.1/css/ionicons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/halamanArtikel.css' %}">

</head>

<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('https://3.bp.blogspot.com/-7e6skWMM4iI/XGav5UtyXVI/AAAAAAAAGyU/LXKJ8E1CGpIvBE3MPqRzjIoaiYSivfS6QCLcBGAs/w1200-h630-p-k-no-nu/pexes%2Bzero%2Bwaste.jpeg')">
        <div class="overlay"></div>
        <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
                <h1 style="font-family: 'Caveat', cursive !important; font-weight: 700 !important;">SoLink</h1>
                <span class="subheading">Platform Pendukung Gaya Hidup Zero Waste</span>
            </div>
            </div>
        </div>
        </div>
    </header>
    <div class="blog">
        <div class="container">
          <div class="row">
  
            {% for obj in artikel %}
            <div class="col-sm-6 col-md-6 item">
              <div class="body">
                <a href="{% url 'article:melihatArtikel' obj.idArtikel %}" class="view"><i class="ion-ios-book-outline"></i></a>
                <a href="{% url 'article:melihatArtikel' obj.idArtikel %}">
                  <img src="{{ obj.gambarThumbnail.url }}">
                </a>
                
                <div class="caption">
                  <h1>{{ obj.judulArtikel }}</h1>
                  <label>{{ obj.timestamp }}</label>
                  <hr class="offset-sm">
  
                  <p>
                    {{ obj.abstraksiArtikel }}
                  </p>
                  <hr class="offset-sm">
  
                  <a href="{% url 'article:melihatArtikel' obj.idArtikel %}">Baca selengkapnya <i class="ion-ios-arrow-right"></i> </a>
                </div>
              </div>
            </div>
            {% endfor %}
  
          </div>
  
          <!-- <nav >
            <ul class="pagination justify-content-center">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
              </li>
              <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
              </li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#">&raquo;</a>
              </li>
            </ul>
          </nav> -->
  
        </div>
    </div>
    <br>
</body>
</html>

article/templates/melihatArtikel.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoLink</title>
    <link href="{% static 'ionicons-2.0.1/css/ionicons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/melihatArtikel.css' %}">

</head>

<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    {% for obj in artikel %}
    <div class="blog-item">
        <a class="header" href="{{ obj.gambarThumbnail.url }}">
            <img src="{{ obj.gambarThumbnail.url }}">
        </a>
        <div class="container">
            <br><br>
	    	<div class="row">
	    		<div class="col-md-8 offset-md-2">
	    			<h1>{{ obj.judulArtikel }}</h1>
		    		 <br>
                        {{ obj.isiArtikel | safe }}
                     <br>
		    		 <button class="btn btn-primary btn-sm facebook"> <i class="ion-social-facebook"></i> Share </button>
		    		 <button class="btn btn-primary btn-sm twitter"> <i class="ion-social-twitter"></i> Retweet</button>
		    		 <button class="btn btn-primary btn-sm googleplus"> <i class="ion-social-googleplus"></i> Plus </button>

                     <hr style="margin: 50px auto 50px; border-top: 2px solid #e2e2e2;"> 
                     <div class="row">
                        <div class="col-md-10 offset-md-1">
                            <h5>Baca artikel lainnya...</h5>
                            <div id="custCarousel" class="carousel slide" data-ride="carousel" align="center">
                                <!-- slides -->
                                <div class="carousel-inner">
                                    <div class="carousel-item active"> 
                                        <a href="{% url 'article:melihatArtikel' 6 %}">
                                            <img src="{% static 'img/kompos.jpg' %}">
                                        </a>
                                        <h3 class="title-img">Manfaat Mengompos Di Rumah</h3>
                                    </div>
                                    <div class="carousel-item "> 
                                        <a href="{% url 'article:melihatArtikel' 2 %}">
                                            <img src="{% static 'img/zerowaste.jpg' %}">
                                        </a>
                                        <h3 class="title-img">Menerapkan Zero Waste Lifestyle di Masa Pandemi</h3>
                                    </div>
                                    <div class="carousel-item "> 
                                        <a href="{% url 'article:melihatArtikel' 4 %}">
                                            <img src="{% static 'img/kamar mandi.jpg' %}">
                                        </a>
                                        <h3 class="title-img">Sikap Bijak Menggunakan Listrik di Kamar Mandi</h3>
                                    </div>
                                    <div class="carousel-item "> 
                                        <a href="{% url 'article:melihatArtikel' 3 %}">
                                            <img src="{% static 'img/grocery.jpeg' %}">
                                        </a>
                                        <h3 class="title-img">Tips Zero Waste Untuk Grocery Shopping</h3>
                                    </div>
                                </div> <!-- Left right --> <a class="carousel-control-prev" href="#custCarousel" data-slide="prev"> <span class="carousel-control-prev-icon"></span> </a> <a class="carousel-control-next" href="#custCarousel" data-slide="next"> <span class="carousel-control-next-icon"></span> </a> <!-- Thumbnails -->
                                <ol class="carousel-indicators list-inline">
                                    <li class="list-inline-item active"> <a id="carousel-selector-0" class="selected" data-slide-to="0" data-target="#custCarousel"> <img src="{% static 'img/kompos.jpg' %}" class="img-fluid"> </a> </li>
                                    <li class="list-inline-item"> <a id="carousel-selector-1" data-slide-to="1" data-target="#custCarousel"> <img src="{% static 'img/zerowaste.jpg' %}" class="img-fluid"> </a> </li>
                                    <li class="list-inline-item"> <a id="carousel-selector-2" data-slide-to="2" data-target="#custCarousel"> <img src="{% static 'img/kamar mandi.jpg' %}" class="img-fluid"> </a> </li>
                                    <li class="list-inline-item"> <a id="carousel-selector-2" data-slide-to="3" data-target="#custCarousel"> <img src="{% static 'img/grocery.jpeg' %}" class="img-fluid"> </a> </li>
                                </ol>
                            </div>
                        </div>
                     </div>
                     <br><br>
                    
	    		</div>
            </div>
        </div>
        
        <br>
    </div>
    {% endfor %}
</body>
{% if message != "" %}
<script>
    alert('{{ message }}');
</script>
{% endif %}
</html>

article/templates/membuatArtikel.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoLink</title>
    <link href="{% static 'ionicons-2.0.1/css/ionicons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/membuatArtikel2.css' %}">

</head>

<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    <div class="create-artikel col-md-10 offset-md-1">
        <br>
        <h3 style="text-align: center; padding:28px 0px 20px; font-weight: bolder;">Form Pembuatan Artikel</h3>
        <form method="POST" action="{% url 'article:membuatArtikel' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.media }}
          {{ form.as_p }}
          
        <br><br><br>
        <a class="btn btn-light" href="{% url 'article:mengelolaArtikel' %}" role="button">Batalkan</a>
        <input type="submit" name="submit" value ="Create" class="btn btn-primary" >
        </form>
        <!-- <br><br><br>
        <button type="button" class="btn btn-light">Batalkan</button>
        <a class="btn btn-primary" href="{% url 'article:halamanArtikel' %}" role="button">Simpan</a> -->
    </div>
</body>


</html>

article/templates/mengelolaArtikel.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoLink</title>
    <link href="{% static 'ionicons-2.0.1/css/ionicons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mengelolaArtikel2.css' %}">

</head>

<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    {% if message != "" %}
        {% if "Gagal" in message %}
        <div class="alert alert-danger alert-dismissible">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissible" >
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endif %}
    <h2 style="text-align: center; padding:28px 0px 20px; font-weight: bolder;">Halaman Kelola Artikel</h2>
    <div class="container">
        <div class="row">
        <div class="col-md-10 offset-md-1">
            <a class="btn btn-success" href="{% url 'article:membuatArtikel' %}" role="button">Buat Artikel &#43;</a>
            <br><br>

            {% for obj in artikel %}
            <div class="post-preview">
            <a href="{% url 'article:melihatArtikel' obj.idArtikel %}">
                <h2 class="post-title">
                    {{ obj.judulArtikel }}
                </h2>
                <h3 class="post-subtitle">
                    {{ obj.abstraksiArtikel|truncatechars:85 }}
                </h3>
            </a>
            <p class="post-meta">{{ obj.timestamp }}
            </p>
            <a class="btn btn-light" href="{% url 'article:mengubahArtikel' obj.idArtikel %}" role="button">Ubah</a>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{ obj.idArtikel }}">Hapus</button> 
            </div>
            <hr>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal{{ obj.idArtikel }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Pesan Konfirmasi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                    Judul : {{ obj.judulArtikel }}
                    <br>
                    Apakah anda yakin ingin menghapus artikel tersebut?
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <!-- <button type="button" class="btn btn-danger">Hapus</button> -->
                    <a href="{% url 'article:menghapusArtikel' obj.idArtikel %}">
                        <button class="btn btn-danger">Hapus</button>
                    </a>            
                    </div>
                </div>
                </div>
            </div>
            {% endfor %}

        </div>
        </div>
    </div>
</body>
<!-- {% if message != "" %}
<script>
    alert('{{ message }}');
</script>
{% endif %} -->
</html>

article/templates/mengubahArtikel.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoLink</title>
    <link href="{% static 'ionicons-2.0.1/css/ionicons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/membuatArtikel2.css' %}">

</head>

<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    <div class="create-artikel col-md-10 offset-md-1">
        <br>
        <h3 style="text-align: center; padding:28px 0px 20px; font-weight: bolder;">Form Ubah Artikel</h3>
        <form  method="POST" action="{% url 'article:mengubahArtikel' idArtikel %}" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.media }}
          {{ form.as_p }}
          
        <br><br><br>
        <a class="btn btn-light" href="{% url 'article:mengelolaArtikel' %}" role="button">Batalkan</a>
        <input type="submit" name="submit" value ="Update" class="btn btn-primary" >
        </form>
        <!-- <br><br><br>
        <button type="button" class="btn btn-light">Batalkan</button>
        <a class="btn btn-primary" href="{% url 'article:halamanArtikel' %}" role="button">Simpan</a> -->
    </div>
</body>


</html>