shop/urls.py
from django.urls import path
from .views import shoppage, checkout, riwayat, deskripsi, tambahBarangKeranjang, keranjangModal, hapusBarangKeranjang, checkoutModal, createTrx, riwayatModal, pembayaranTrx, konfirmasiSampai

app_name = 'shop'

urlpatterns = [
    path('', shoppage, name='shoppage'),
    path('pembayaran/<id>', checkout, name='checkout'),
    path('riwayat_transaksi/', riwayat, name='riwayat'),
    path('deskripsi/<id>/', deskripsi, name='deskripsi'),
    path('tambah_barang_keranjang/', tambahBarangKeranjang, name='tambahBarangKeranjang'),
    path('modal_keranjang/', keranjangModal, name='keranjangModal'),
    path('modal_checkout/', checkoutModal, name='checkoutModal'),
    path('modal_riwayat/', riwayatModal, name='riwayatModal'),
    path('hapus_barang_keranjang/', hapusBarangKeranjang, name='hapusBarangKeranjang'),
    path('create_transaksi/', createTrx, name='createTrx'),
    path('pembayaran/', pembayaranTrx, name='pembayaran'),
    path('sampai/', konfirmasiSampai, name='pembayaran'),
]

solink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('shop/', include('shop.urls')),
    path('barang/', include('barang.urls')),
    path('donasi/', include('donasi.urls')),
    path('mitra/', include('shop.mitra_urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loginin/', include('loginin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from barang.models import Barang
from django.core.validators import MinValueValidator

# Create your models here.
class KeranjangModel(models.Model):
    def hitungTotal(self):
        total = 0
        for barang in self.barangkeranjang_set.all():
            total += barang.subtotal()
        return total

class BarangKeranjang(models.Model):
    barang = models.ForeignKey(Barang, on_delete=models.CASCADE)
    qty = models.IntegerField(validators=[MinValueValidator(1)])
    keranjang = models.ForeignKey(KeranjangModel, on_delete=models.CASCADE)

    def subtotal(self):
        return self.barang.hargaBarang * self.qty

class KontributorModel(models.Model):
    pengguna = models.OneToOneField(User, on_delete=models.CASCADE)
    urlFotoDiriDenganKtp = models.TextField()
    urlFotoKTP = models.TextField()
    keranjang = models.OneToOneField(KeranjangModel, on_delete=models.CASCADE, null=True, blank=True)

class TransaksiModel(models.Model):
    waktuDibuat = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20)
    totalHarga = models.FloatField()
    metodePengiriman = models.CharField(max_length=10, null=True)
    kontributor = models.ForeignKey(KontributorModel, on_delete=models.CASCADE)

class BarangTrx(models.Model):
    barangTrx = models.ForeignKey(Barang, on_delete=models.CASCADE)
    qtyTrx = models.IntegerField(validators=[MinValueValidator(1)])
    transaksi = models.ForeignKey(TransaksiModel, on_delete=models.CASCADE)

    def subtotal(self):
        return self.barangTrx.hargaBarang * self.qtyTrx

class PembayaranModel(models.Model):
    waktuPembayaran = models.DateTimeField(auto_now_add=True)
    totalPembayaran = models.FloatField()
    transaksi = models.OneToOneField(TransaksiModel, on_delete=models.CASCADE)

class PengirimanModel(models.Model):
    namaEkspedisi = models.CharField(max_length=100)
    nomorResi = models.CharField(max_length=20)
    transaksi = models.OneToOneField(TransaksiModel, on_delete=models.CASCADE)

shop/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from loginin.Pengguna import Pengguna
from barang.models import Barang
from .models import KontributorModel, TransaksiModel, KeranjangModel
from .Kontributor import Kontributor
from django.http.response import JsonResponse
from loginin.Mitra import Mitra
from django.http import HttpResponse

# Create your views here.
pengguna = Pengguna("dummy", "dummy@dummy.com", "dummy", "dummy", "dummy", "dummy")
mitra = Mitra("namaMitra")
kontributorDict = {}

def getKontributor(uname):
    kontributorDBcount = KontributorModel.objects.all().count()
    if kontributorDBcount == len(kontributorDict):
        pass
    else:
        for el in KontributorModel.objects.all():
            kontributorDict[el.pengguna.username] = Kontributor(el, el.pengguna.username, el.pengguna.email, el.pengguna.username, el.pengguna.password, "08123456789", "Kampus Baru UI, Margonda Raya, Depok 12345")

    if uname in kontributorDict.keys():
        return kontributorDict[uname]
    else:
        penggunaModel = User.objects.get(username=uname)
        keranjang = KeranjangModel()
        keranjang.save()
        kontributorModel = KontributorModel(pengguna=penggunaModel, urlFotoDiriDenganKtp="urlFotoDiriDenganKtp", urlFotoKTP="urlFotoKTP", keranjang=keranjang)
        kontributorModel.save()
        kontributor = Kontributor(kontributorModel, penggunaModel.username, penggunaModel.email, penggunaModel.username, penggunaModel.password, "08123456789", "Kampus Baru UI, Margonda Raya, Depok 12345")
        kontributorDict[uname] = kontributor
        return kontributor

def shoppage(request):
    data = pengguna.melihatBarang()
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            return render(request, 'shoppage.html',{'data': data, 'keranjang': kontributor.getKeranjang()})
    return render(request, 'shoppage.html',{'data': data})

def checkout(request, id):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            trx = kontributor.getTransaksi(int(id))
            biaya = trx.getTotalHarga()
            return render(request, 'checkoutSuccess.html', {'biaya':biaya})
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def riwayat(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            lst = kontributor.getAllTransaksi().values()
            listTransaksi = []
            for el in lst:
                id = el.getId()
                totalItem = el.getTotalBarang()
                totalHarga = el.getTotalHarga()
                status = el.getStatus()
                metodePengiriman = el.getMetodePengiriman()
                ekspedisi = ""
                resi = ""
                if status == 'Sedang Dikirim' or status == 'Selesai':
                    ekspedisi = el.getTrxModel().pengirimanmodel.namaEkspedisi
                    resi = el.getTrxModel().pengirimanmodel.nomorResi
                listTransaksi.append((id, totalItem, totalHarga, metodePengiriman, status, ekspedisi, resi))
            return render(request, 'riwayat.html', {'listTransaksi':listTransaksi})
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def deskripsi(request,id):
    data = Barang.objects.get(idBarang=id)
    return render(request, 'deskripsiBarang.html',{'data':data})

@csrf_exempt
def tambahBarangKeranjang(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            jsonRslt = {}
            if request.method == "POST":
                idBarang = request.POST["idBarang"]
                result = kontributor.tambahBarangKeranjang(idBarang)
                jsonRslt['nama'] = result
            return JsonResponse(jsonRslt)
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def keranjangModal(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            keranjang = kontributor.getKeranjang()
            listBarang = keranjang.getModel().barangkeranjang_set.all()
            jsonRslt = {}
            count = 0
            for el in listBarang:
                count +=1
                barangJson = {}
                barangJson['nama'] = el.barang.namaBarang
                barangJson['harga'] = el.barang.hargaBarang
                barangJson['id'] = el.id
                jsonRslt[count] = barangJson
            jsonRslt['count'] = count
            jsonRslt['total'] = keranjang.hitungTotal()
            return JsonResponse(jsonRslt)
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

@csrf_exempt
def hapusBarangKeranjang(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            if request.method == "POST":
                idBarang = request.POST["idBarang"]
                barangTrx = kontributor.getKeranjang().getModel().barangkeranjang_set.all().get(id=idBarang)
                barangTrx.delete()
            return JsonResponse({})
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def checkoutModal(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            keranjang = kontributor.getKeranjang()
            listBarang = keranjang.getModel().barangkeranjang_set.all()
            jsonRslt = {}
            count = 0
            for el in listBarang:
                count +=1
                barangJson = {}
                barangJson['nama'] = el.barang.namaBarang
                barangJson['harga'] = el.barang.hargaBarang
                barangJson['id'] = el.id
                jsonRslt[count] = barangJson
            jsonRslt['count'] = count
            jsonRslt['total'] = keranjang.hitungTotal()
            jsonRslt['alamat'] = kontributor.getAlamat()
            return JsonResponse(jsonRslt)
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

@csrf_exempt
def createTrx(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            if request.method == "POST":
                totalHarga = request.POST['total']
                metode = request.POST['metode']
                trxId = kontributor.createTransaksi(totalHarga, metode, kontributor.getModel(), mitra)
            return JsonResponse({'id':trxId})
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def riwayatModal(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            idTransaksi = request.GET['id']
            transaksi = kontributor.getTransaksi(int(idTransaksi))
            jsonRslt = {}
            count = 0
            ongkir = transaksi.getTotalHarga()
            for el in transaksi.getListBarang():
                count +=1
                barangJson = {}
                barangJson['nama'] = el.barangTrx.namaBarang
                barangJson['harga'] = el.barangTrx.hargaBarang
                barangJson['qty'] = el.qtyTrx
                barangJson['subtotal'] = el.subtotal()
                jsonRslt[count] = barangJson
                ongkir -= el.subtotal()
            jsonRslt['id'] = transaksi.getId()
            jsonRslt['status'] = transaksi.getStatus()
            jsonRslt['metode'] = transaksi.getMetodePengiriman()
            jsonRslt['ongkir'] = ongkir
            jsonRslt['count'] = count
            jsonRslt['total'] = transaksi.getTotalHarga()
            return JsonResponse(jsonRslt)
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def pembayaranTrx(request):
    if request.user.is_authenticated:
        if request.user.profile.role == "Kontributor/Pembeli":
            kontributor = getKontributor(request.user.username)
            idTransaksi = request.GET['id']
            kontributor.pembayaran(int(idTransaksi))
            jsonRslt = {'id':idTransaksi}
            return JsonResponse(jsonRslt)
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

def penjualan(request): 
    lst = TransaksiModel.objects.exclude(status='Menunggu Pembayaran')
    listTransaksi = []
    for el in lst:
        id = el.id
        pembeli = el.kontributor.pengguna.username
        totalItem = el.barangtrx_set.all().count()
        totalBayar = el.pembayaranmodel.totalPembayaran
        status = el.status
        listTransaksi.append((id,pembeli, totalItem, totalBayar, status))
    return render(request, 'mitra/mtr_shop.html', {'listTrx':listTransaksi})

def pengiriman(request, id):
    return render(request, 'mitra/mtr_pengiriman.html', {'id':id})
    return HttpResponse("Kamu harus masuk sebagai <b>Kontributor/Pembeli</b> untuk melihat halaman ini")

@csrf_exempt
def pengirimanDone(request):
    if request.method == "POST":
        idTrx = request.POST['id']

shop/templates/checkoutSuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaksi Berhasil! - SoLink</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        .brand {
            font-family: 'Caveat', cursive;
            font-weight: 700;
        }
        .liCO {
            margin-bottom: 2%;
        }
    </style>
</head>
<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    <div class="container" style="margin-top: 2%;">
        <div class="row">
            <div class="col">
                <div class="card border-secondary" style="background-color: transparent;">
                    <div class="card-body" style="padding: 0.5rem; text-align: center;">
                      Transaksi berhasil! Terima kasih telah berbelanja di <span class="brand">SoLink</span> !
                    </div>
                  </div>
            </div>
        </div>
        <div class="row">
            <div class="col" style="text-align: center; margin-top: 2%;">
                <h3>Total Biaya Transaksi: {{biaya}}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col" style="text-align: center;">
                <h1 class="brand" style="font-weight: 400;">Tata Cara Pembayaran</h1>
            </div>
        </div>
        <div class="row justify-content-center" style="margin-top: 1%;">
            <div class="col-12 col-sm-6" style="text-align: left;">
                <ol>
                    <li class="liCO">
                        Setor uang atau uang elektronik (contoh: DANA, OVO, LinkAja, dll.) ke rekening bank SoLink berikut: <b>1234567890</b>.
                        Pastikan nominal yang Anda setorkan sesuai dengan total biaya pada transaksi.
                    </li>
                    <li class="liCO">Setelah melakukan pembayaran, harap melakukan konfirmasi pembayaran yang dapat dilakukan di halaman Riwayat Transaksi.</li>
                    <li class="liCO">Transaksi Anda akan diteruskan kepada Mitra ketika pembayaran telah dikonfirmasi.</li>
                </ol>
                <br>
                <a href="{% url 'shop:riwayat' %}"><button type="button" class="btn btn-outline-dark" style="float: right;">Lihat Riwayat Transaksi</button></a>
            </div>
        </div>
    </div>
</body>
</html>

shop/templates/deskripsiBarang.html
{% extends "navbar.html" %}

{% block content %}
<script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
<div class="container" style="margin-top: 2%;">
    <div class="row">
        <div class="col-8">
            <h1 style="font-family: 'Caveat', cursive;">Zero Waste Shop</h1>
        </div>
        <div class="col-2">
            <a href="{% url 'shop:shoppage' %}">
                <button type="button" class="btn btn-outline-dark" style="float: right;">
                    Kembali 
                </button>
            </a>
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-outline-dark" style="float: right;" onclick="modalKeranjang()" data-toggle="modal" data-target="#keranjangModal">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                </svg>
                Keranjang
            </button>
        </div>
    </div>
    <div class="container h-100">
        <div class="row row-cols-2 row-cols-sm-4 h-100" style="margin-top: 2%;">
            <div class="col-sm-4 justify-content-center align-self-center h-100">
                <div class="card">
                    <img src="{{ data.urlFoto }}" class="card-img-top">
                    <div class="card-body">
                        <div class="text-right">    
                            <a href="javascript:tambahBarangKeranjang({{ data.idBarang }});">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                    <path fill-rule="evenodd" d="M8.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 .5-.5z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-8 justify-content-center align-self-center h-100">
                <div class="card">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-4"><h4>Nama Barang</h4> </div>
                            <div class="col-sm-8"><h4>: {{ data.namaBarang }} </h4></div>
                        </div>
                        <div class="row">
                            <div class="col-4"><h4>Harga</h4> </div>
                            <div class="col-8"><h4>: Rp. {{ data.hargaBarang }} </h4></div>
                        </div>
                        <div class="row">
                            <div class="col-4"><h4>Rating </h4></div>
                            <div class="col-8"><h4>: {{ data.rating }} </h4></div>
                        </div>
                        <div class="row">
                            <div class="col-4"><h4>Penjual</h4> </div>
                            <div class="col-8"><h4>: {{ data.namaPemilik }} </h4></div>
                        </div>
                        <div class="row">
                            <div class="col-4"><h4>Stok</h4> </div>
                            <div class="col-8"><h4>: {{ data.jumlahStok }}</h4> </div>
                        </div>
                        <div class="row">
                            <div class="col-4"><h4>Deskripsi</h4> </div>
                            <div class="col-8"><h4>{{ data.deskripsiBarang }}</h4> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'keranjangModal.html' %}
    {% include 'pengirimanModal.html' %}

    <script>
        function tambahBarangKeranjang(idBarang) {
            $.ajax({
                type : "POST",
                url : "/shop/tambah_barang_keranjang/",
                data : {
                    'idBarang' : idBarang
                },
                success : function(result) {
                    alert(result['nama'] + " berhasil dimasukkan ke keranjang!")
                },
                error : function() {
                    alert("Barang gagal dimasukkan ke keranjang. Harap coba lagi setelah beberapa saat.")
                }
            })
        }
    </script>
{% endblock%}

shop/templates/shoppage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zero Waste Shop - SoLink</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        img {
            object-fit: contain;
            max-height: 250px;
        }
        h5 {
            font-weight: 600;
        }
        .hargaKeranjang {
            font-size: 70%;
        }
        .wrap{
          position: relative;
        }
        .wrap a{
          position: absolute;
          width:100%;
          height:100%;
          top:0px;
          left:0px;
        }
    </style>
</head>
<body style="background-color: #bbd4ce; font-family: 'Nunito', sans-serif;">
    {% include 'navbar.html' %}
    <div class="container" style="margin-top: 2%;">
        <div class="row">
            <div class="col-8">
                <h1 style="font-family: 'Caveat', cursive;">Zero Waste Shop</h1>
            </div>
            {% if keranjang %}
            <div class="col-2">
                <a href="{% url 'shop:riwayat' %}">
                    <button type="button" class="btn btn-outline-dark" style="float: right;">
                        Riwayat Transaksi
                    </button>
                </a>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-outline-dark" style="float: right;" onclick="modalKeranjang()" data-toggle="modal" data-target="#keranjangModal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                    </svg>
                    Keranjang
                </button>
            </div>
            {% endif %}
        </div>
        <div class="row row-cols-2 row-cols-sm-4" style="margin-top: 1%;">
          {% for item in data %}
          <div class="col mb-4">
            <div class="card h-100 wrap">
              <a href="{% url 'shop:deskripsi' item.idBarang %}"></a>
              <img src="{{ item.urlFoto }}" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title">{{ item.namaBarang }}</h5>
                <div class="text-right">
                    <p class="card-text">{{ item.hargaBarang }}</p>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
    </div>

    {% include 'keranjangModal.html' %}
    {% include 'pengirimanModal.html' %}

</body>
</html>